Arch\AdminBundle\Entity\Personal:
  type: entity
  table: personal
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    pib:
      type: string
      length: 255
      fixed: false
      nullable: false
    birthday:
      type: date
      nullable: false
  oneToOne:
    department:
      targetEntity: Department
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        department_id:
          referencedColumnName: id
      orphanRemoval: false
    position:
      targetEntity: Position
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        position_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
