Arch\AdminBundle\Entity\Position:
  type: entity
  table: position
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    name:
      type: string
      length: 45
      fixed: false
      nullable: true
  lifecycleCallbacks: {  }
