<?php

namespace Arch\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SoftwareRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoftwareRepository extends EntityRepository
{
    public function findAll()
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('s, t, l')
            ->from('ArchAdminBundle:Software', 's')
            ->join('s.softwareType', 't')
            ->join('s.license', 'l');
        $res = $qb->getQuery()->getResult();

        return $res;
    }
}